# Generated by Django 5.0.7 on 2024-10-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_feedback_phone_no_alter_feedback_feedback_text'),
        ('facultyapp', '0002_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advance Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development')], max_length=50)),
                ('marks', models.IntegerField()),
                ('studnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
