# Generated by Django 5.0.7 on 2024-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='studnt',
            new_name='student',
        ),
    ]
