# Generated by Django 5.0.7 on 2024-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(max_length=150),
        ),
    ]
